apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sssssssssssssssample-java-springboot-basic-yjxh
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sssssssssssssssample-java-springboot-basic-yjxh
    app.kubernetes.io/part-of: my-app-lllllllllllllll
  name: devfile-sssssssssssssssample-java-springboot-basic-yjxh
  namespace: rsoaresd-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: devfile-sssssssssssssssample-java-springboot-basic-yjxh
    weight: null
status: {}
