apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sssssssssssssssample-java-springboot-basic-yjxh
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sssssssssssssssample-java-springboot-basic-yjxh
    app.kubernetes.io/part-of: my-app-lllllllllllllll
  name: devfile-sssssssssssssssample-java-springboot-basic-yjxh
  namespace: rsoaresd-tenant
spec:
  ports:
  - name: http-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: java-springboot-app
    app.kubernetes.io/instance: devfile-sssssssssssssssample-java-springboot-basic-yjxh
status:
  loadBalancer: {}
